### PR TITLE
1.21.5

### PR DESCRIPTION
**Pull request by throwRuntime**
The plugin did not work correctly on version 1.21.5 (I did not test it on higher versions). It gave the following error:

```
[FakeSnow] Unhandled exception number 128 occurred in onPacketSending(PacketEvent) for FakeSnow
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/CraftChunk
  at FakeSnow-1.3.3.jar/com.jacky8399.fakesnow.v1_21_1_R1.PacketListener_v1_21_1_R1.updatePacketOld(PacketListener_v1_21_1_R1.java:149) ~[FakeSnow-1.3.3.jar:?]
  at FakeSnow-1.3.3.jar/com.jacky8399.fakesnow.v1_21_1_R1.PacketListener_v1_21_1_R1.onPacketSending(PacketListener_v1_21_1_R1.java:348) ~[FakeSnow-1.3.3.jar:?]
```

When I recompiled the plugin and added support for 1.21.5 (by simply copying the code for 1.21.4), the "old packet handler" started working, but "fast packet handler" for some reason kicks players with the error "Network Protocol Error".

In general, the code from this pull request fixes the compilation and makes it possible to use the plugin on version 1.21.5 using the "old packet handler" without errors.

### CODE REVIEW

**Comment by throwRuntime** [comment]
Just now I noticed that in issues you already dropped a plugin that works with 1.21.5/1.21.6. However, I don't understand why you haven't committed this code to the repository. Please update the plugin if possible.

**Comment by jacky8399** [comment]
Thanks for the PR. I'll look into the network error when I have time. However, I don't believe I have updated the plugin past 1.21.4. Could you tell me where you saw the updated version of the plugin?

**Comment by throwRuntime** [comment]
https://github.com/jacky8399/FakeSnow/issues/7#issuecomment-2591464146

**Comment by jacky8399** [comment]
That's for 1.20.6.

**Comment by throwRuntime** [comment]
> This jar is built against 1.20.5/6, but I don't have a 1.20.6 testing environment so it's untested. [FakeSnow-1.3.3-1.20.6fork.jar.zip](https://github.com/user-attachments/files/18298253/FakeSnow-1.3.3-1.20.6fork.jar.zip)

https://github.com/jacky8399/FakeSnow/issues/7#issuecomment-2568948394

**Comment by jacky8399** [comment]
I made some additional changes to the code, but thanks for the PR regardless. [Version 1.4](https://github.com/jacky8399/FakeSnow/releases/tag/1.4) now supports Paper 1.21.5+.

**Comment by throwRuntime** [comment]
It's okay. Thank you very much!!
